/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R403RouteImport } from './routes/403'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as _publicRouteRouteImport } from './routes/__public/route'
import { Route as _authRouteRouteImport } from './routes/__auth/route'
import { Route as _publicIndexRouteImport } from './routes/__public/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as _publicAboutRouteImport } from './routes/__public/about'
import { Route as _authLoginRouteImport } from './routes/__auth/login'
import { Route as AdminSubcategoriesListRouteImport } from './routes/admin/subcategories/list'
import { Route as AdminSubcategoriesCreateRouteImport } from './routes/admin/subcategories/create'
import { Route as AdminProductTypesListRouteImport } from './routes/admin/product-types/list'
import { Route as AdminProductTypesCreateRouteImport } from './routes/admin/product-types/create'
import { Route as AdminCategoriesTestRouteImport } from './routes/admin/categories/test'
import { Route as AdminCategoriesListRouteImport } from './routes/admin/categories/list'
import { Route as AdminCategoriesCreateRouteImport } from './routes/admin/categories/create'
import { Route as AdminCategoriesDetailIdTestRouteImport } from './routes/admin/categories/detail/$id/test'
import { Route as AdminCategoriesDetailIdSlugRouteImport } from './routes/admin/categories/detail/$id/$slug'

const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const _publicRouteRoute = _publicRouteRouteImport.update({
  id: '/__public',
  getParentRoute: () => rootRouteImport,
} as any)
const _authRouteRoute = _authRouteRouteImport.update({
  id: '/__auth',
  getParentRoute: () => rootRouteImport,
} as any)
const _publicIndexRoute = _publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _publicRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const _publicAboutRoute = _publicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => _publicRouteRoute,
} as any)
const _authLoginRoute = _authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => _authRouteRoute,
} as any)
const AdminSubcategoriesListRoute = AdminSubcategoriesListRouteImport.update({
  id: '/subcategories/list',
  path: '/subcategories/list',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubcategoriesCreateRoute =
  AdminSubcategoriesCreateRouteImport.update({
    id: '/subcategories/create',
    path: '/subcategories/create',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminProductTypesListRoute = AdminProductTypesListRouteImport.update({
  id: '/product-types/list',
  path: '/product-types/list',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductTypesCreateRoute = AdminProductTypesCreateRouteImport.update({
  id: '/product-types/create',
  path: '/product-types/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesTestRoute = AdminCategoriesTestRouteImport.update({
  id: '/categories/test',
  path: '/categories/test',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesListRoute = AdminCategoriesListRouteImport.update({
  id: '/categories/list',
  path: '/categories/list',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesCreateRoute = AdminCategoriesCreateRouteImport.update({
  id: '/categories/create',
  path: '/categories/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesDetailIdTestRoute =
  AdminCategoriesDetailIdTestRouteImport.update({
    id: '/categories/detail/$id/test',
    path: '/categories/detail/$id/test',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCategoriesDetailIdSlugRoute =
  AdminCategoriesDetailIdSlugRouteImport.update({
    id: '/categories/detail/$id/$slug',
    path: '/categories/detail/$id/$slug',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/403': typeof R403Route
  '/login': typeof _authLoginRoute
  '/about': typeof _publicAboutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/': typeof _publicIndexRoute
  '/admin/categories/create': typeof AdminCategoriesCreateRoute
  '/admin/categories/list': typeof AdminCategoriesListRoute
  '/admin/categories/test': typeof AdminCategoriesTestRoute
  '/admin/product-types/create': typeof AdminProductTypesCreateRoute
  '/admin/product-types/list': typeof AdminProductTypesListRoute
  '/admin/subcategories/create': typeof AdminSubcategoriesCreateRoute
  '/admin/subcategories/list': typeof AdminSubcategoriesListRoute
  '/admin/categories/detail/$id/$slug': typeof AdminCategoriesDetailIdSlugRoute
  '/admin/categories/detail/$id/test': typeof AdminCategoriesDetailIdTestRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteRouteWithChildren
  '/403': typeof R403Route
  '/login': typeof _authLoginRoute
  '/about': typeof _publicAboutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/': typeof _publicIndexRoute
  '/admin/categories/create': typeof AdminCategoriesCreateRoute
  '/admin/categories/list': typeof AdminCategoriesListRoute
  '/admin/categories/test': typeof AdminCategoriesTestRoute
  '/admin/product-types/create': typeof AdminProductTypesCreateRoute
  '/admin/product-types/list': typeof AdminProductTypesListRoute
  '/admin/subcategories/create': typeof AdminSubcategoriesCreateRoute
  '/admin/subcategories/list': typeof AdminSubcategoriesListRoute
  '/admin/categories/detail/$id/$slug': typeof AdminCategoriesDetailIdSlugRoute
  '/admin/categories/detail/$id/test': typeof AdminCategoriesDetailIdTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__auth': typeof _authRouteRouteWithChildren
  '/__public': typeof _publicRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/403': typeof R403Route
  '/__auth/login': typeof _authLoginRoute
  '/__public/about': typeof _publicAboutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/__public/': typeof _publicIndexRoute
  '/admin/categories/create': typeof AdminCategoriesCreateRoute
  '/admin/categories/list': typeof AdminCategoriesListRoute
  '/admin/categories/test': typeof AdminCategoriesTestRoute
  '/admin/product-types/create': typeof AdminProductTypesCreateRoute
  '/admin/product-types/list': typeof AdminProductTypesListRoute
  '/admin/subcategories/create': typeof AdminSubcategoriesCreateRoute
  '/admin/subcategories/list': typeof AdminSubcategoriesListRoute
  '/admin/categories/detail/$id/$slug': typeof AdminCategoriesDetailIdSlugRoute
  '/admin/categories/detail/$id/test': typeof AdminCategoriesDetailIdTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/403'
    | '/login'
    | '/about'
    | '/admin/dashboard'
    | '/'
    | '/admin/categories/create'
    | '/admin/categories/list'
    | '/admin/categories/test'
    | '/admin/product-types/create'
    | '/admin/product-types/list'
    | '/admin/subcategories/create'
    | '/admin/subcategories/list'
    | '/admin/categories/detail/$id/$slug'
    | '/admin/categories/detail/$id/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/403'
    | '/login'
    | '/about'
    | '/admin/dashboard'
    | '/'
    | '/admin/categories/create'
    | '/admin/categories/list'
    | '/admin/categories/test'
    | '/admin/product-types/create'
    | '/admin/product-types/list'
    | '/admin/subcategories/create'
    | '/admin/subcategories/list'
    | '/admin/categories/detail/$id/$slug'
    | '/admin/categories/detail/$id/test'
  id:
    | '__root__'
    | '/__auth'
    | '/__public'
    | '/admin'
    | '/403'
    | '/__auth/login'
    | '/__public/about'
    | '/admin/dashboard'
    | '/__public/'
    | '/admin/categories/create'
    | '/admin/categories/list'
    | '/admin/categories/test'
    | '/admin/product-types/create'
    | '/admin/product-types/list'
    | '/admin/subcategories/create'
    | '/admin/subcategories/list'
    | '/admin/categories/detail/$id/$slug'
    | '/admin/categories/detail/$id/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _authRouteRoute: typeof _authRouteRouteWithChildren
  _publicRouteRoute: typeof _publicRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  R403Route: typeof R403Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__public': {
      id: '/__public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth': {
      id: '/__auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__public/': {
      id: '/__public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _publicIndexRouteImport
      parentRoute: typeof _publicRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/__public/about': {
      id: '/__public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof _publicAboutRouteImport
      parentRoute: typeof _publicRouteRoute
    }
    '/__auth/login': {
      id: '/__auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof _authLoginRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/admin/subcategories/list': {
      id: '/admin/subcategories/list'
      path: '/subcategories/list'
      fullPath: '/admin/subcategories/list'
      preLoaderRoute: typeof AdminSubcategoriesListRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/subcategories/create': {
      id: '/admin/subcategories/create'
      path: '/subcategories/create'
      fullPath: '/admin/subcategories/create'
      preLoaderRoute: typeof AdminSubcategoriesCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/product-types/list': {
      id: '/admin/product-types/list'
      path: '/product-types/list'
      fullPath: '/admin/product-types/list'
      preLoaderRoute: typeof AdminProductTypesListRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/product-types/create': {
      id: '/admin/product-types/create'
      path: '/product-types/create'
      fullPath: '/admin/product-types/create'
      preLoaderRoute: typeof AdminProductTypesCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/test': {
      id: '/admin/categories/test'
      path: '/categories/test'
      fullPath: '/admin/categories/test'
      preLoaderRoute: typeof AdminCategoriesTestRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/list': {
      id: '/admin/categories/list'
      path: '/categories/list'
      fullPath: '/admin/categories/list'
      preLoaderRoute: typeof AdminCategoriesListRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/create': {
      id: '/admin/categories/create'
      path: '/categories/create'
      fullPath: '/admin/categories/create'
      preLoaderRoute: typeof AdminCategoriesCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/detail/$id/test': {
      id: '/admin/categories/detail/$id/test'
      path: '/categories/detail/$id/test'
      fullPath: '/admin/categories/detail/$id/test'
      preLoaderRoute: typeof AdminCategoriesDetailIdTestRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/detail/$id/$slug': {
      id: '/admin/categories/detail/$id/$slug'
      path: '/categories/detail/$id/$slug'
      fullPath: '/admin/categories/detail/$id/$slug'
      preLoaderRoute: typeof AdminCategoriesDetailIdSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface _authRouteRouteChildren {
  _authLoginRoute: typeof _authLoginRoute
}

const _authRouteRouteChildren: _authRouteRouteChildren = {
  _authLoginRoute: _authLoginRoute,
}

const _authRouteRouteWithChildren = _authRouteRoute._addFileChildren(
  _authRouteRouteChildren,
)

interface _publicRouteRouteChildren {
  _publicAboutRoute: typeof _publicAboutRoute
  _publicIndexRoute: typeof _publicIndexRoute
}

const _publicRouteRouteChildren: _publicRouteRouteChildren = {
  _publicAboutRoute: _publicAboutRoute,
  _publicIndexRoute: _publicIndexRoute,
}

const _publicRouteRouteWithChildren = _publicRouteRoute._addFileChildren(
  _publicRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminCategoriesCreateRoute: typeof AdminCategoriesCreateRoute
  AdminCategoriesListRoute: typeof AdminCategoriesListRoute
  AdminCategoriesTestRoute: typeof AdminCategoriesTestRoute
  AdminProductTypesCreateRoute: typeof AdminProductTypesCreateRoute
  AdminProductTypesListRoute: typeof AdminProductTypesListRoute
  AdminSubcategoriesCreateRoute: typeof AdminSubcategoriesCreateRoute
  AdminSubcategoriesListRoute: typeof AdminSubcategoriesListRoute
  AdminCategoriesDetailIdSlugRoute: typeof AdminCategoriesDetailIdSlugRoute
  AdminCategoriesDetailIdTestRoute: typeof AdminCategoriesDetailIdTestRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminCategoriesCreateRoute: AdminCategoriesCreateRoute,
  AdminCategoriesListRoute: AdminCategoriesListRoute,
  AdminCategoriesTestRoute: AdminCategoriesTestRoute,
  AdminProductTypesCreateRoute: AdminProductTypesCreateRoute,
  AdminProductTypesListRoute: AdminProductTypesListRoute,
  AdminSubcategoriesCreateRoute: AdminSubcategoriesCreateRoute,
  AdminSubcategoriesListRoute: AdminSubcategoriesListRoute,
  AdminCategoriesDetailIdSlugRoute: AdminCategoriesDetailIdSlugRoute,
  AdminCategoriesDetailIdTestRoute: AdminCategoriesDetailIdTestRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _authRouteRoute: _authRouteRouteWithChildren,
  _publicRouteRoute: _publicRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  R403Route: R403Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
